[package]
name = "lsp_json"
version = "0.1.0"
edition = "2018"

[lib]
path = "src/lib.rs"

[dependencies]
ng_async = { version = "0.1.0", path = "../ng_async" }
emacs = { version = "0.1.0", path = "../emacs" }
lisp-macros = { version = "0.1.0", path = "../lisp_macros" }
lisp-util = { version = "0.1.0", path = "../lisp_util" }
libc.workspace = true
lazy_static.workspace = true
lsp-server = "0.7"
serde_json = { version = "1.0", features = ["preserve_order"] }

[build-dependencies]
ng-bindgen = { path = "../../ng-bindgen" }